### PR TITLE
Automatically detect compatible device profiles

### PR DESCRIPTION
**Pull request by diurnalist**
The coordinator will now inspect the state of the K8s node periodically
and update the device's representation in Doni to reflect the set of
device profiles now supported.

### CODE REVIEW

**Comment by diurnalist** [comment]
[Set device profiles on Blazar device resources for easier reservations](https://trello.com/c/hlGAbLnr/2650-set-device-profiles-on-blazar-device-resources-for-easier-reservations)

**Review by Mark-Powers — APPROVED** [review]
👍

**Review by msherman64 — APPROVED** [review]
Looks good to me overall.
To check my understanding, this is talking directly to the local kublet on the device, rather than querying the controlplane?

If it's only hitting the k8s API, and Zun API, I'm not clear on why this runs on the device, rather than on the controller node.

**Comment by diurnalist** [comment]
@msherman64 it is querying the k8s api server (control plane), but it has an auth token that can only influence state on its own node or pods on its own node. The reason it is not on the control plane is that there is no mechanism for periodic jobs in Doni (a worker update is only triggered when a "sync" happens, or if the user updates the hw entry.) We could have the user trigger a "sync" whenever they plug in a device and document this necessity. However, there is an issue of what happens if the k8s device plugin takes a while, or doesn't have the info by the time Doni scrapes it. If Doni had a periodic mechanism, we could do it there, or if there's some other way I didn't think of to avoid this race condition. That's why it's in the coordinator... but there is definitely a case it should live in Doni for consistency.

**Pull request merged**
